### ISSUE TITLE
Can't Use LogMeIn With Phenix City Locations

### ISSUE THREAD

**Issue by JaRyCu** [TWCMobile/Stores#4]
I'm able to use LogMeIn to access all of the Dawson, Sumiton, & McCalla computers, but I can't get into the Phenix City ones.  When Justin set me up, he told me that I could log in using either 'pcbackright' or 'phenixcitybackright,' for example, but I can't get into that desktop or any other one in the store, either.

What are the codes for the desktops in PC?

**Comment by TWCMobile** [comment]
Will email you the code.
