### ISSUE TITLE
Phenix City / Dawson Reps Not on reps@twc List

### ISSUE THREAD

**Issue by JaRyCu** [TWCMobile/Stores#7]
stephan.hobbs@twcmobile.net
latricia.stephens@twcmobile.net
david.shehane@twcmobile.net
martellis.bennett@twcmobile.net
felicia.jefferson@twcmobile.net
norma.cruz@twcmobile.net

**Comment by TWCMobile** [comment]
Added to Reps email @ 1355 10/9/17
