### ISSUE TITLE
Dawson EOD Totals Not Being Received

### ISSUE THREAD

**Issue by JaRyCu** [TWCMobile/Stores#8]
I did not get the Personal or Store EOD totals from The Wireless Coach last night from Dawson.  I checked with the closing rep this morning and she insists that she did them.

**Comment by TWCMobile** [comment]
Send to 
jason.cunningham@twcmobile.net
 if Dawson (Personal EOD)

Send to	 
jason.cunningham@twcmobile.net
 if Dawson (Store EOD)

@JaRyCu I dont believe your rep's are doing them.
